#!/bin/bash

# Instalacao do Sublime Text
# Johni Douglas Marangon
# 11/2013

APLICACAO="Sublime Text 2.0.2"


# verifica se o usuario tem permissoes root
if  [ "$(id -u)" != "0" ];  then
  echo "Este script precisa ser executado como root"
  exit  1
fi

# confirmacao da instalacao
read -p "   Deseja realmente instalar o ${APLICACAO}  [s/N] " resp
resp=$(echo "$resp" | tr [[:upper:]] [[:lower:]] | cut -c1)

echo "resp $resp"

if [ "$resp" != "s" ]; then
  exit 1	
fi

echo "Iniciando a instalacao do ${APLICACAO}"



# 32
#http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.2.tar.bz2

# 64
#http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.2%20x64.tar.bz2

#wget ${URL} -P /tmp

#tar jxvf  -C ${DirInstalacao}

#chown -R root:root ${DirInstalacao}
#chmod -R +r ${DirInstalacao}

# criar o startes

# limpar os diretorios
